name: fs_auth_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  grpc: ^3.0.2
  protobuf: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
